apiVersion: v1
kind: Service
metadata:
  name: example-application
  namespace: default
  labels:
    app: example-application
spec:
  type: ClusterIP
  selector:
    app: example-application
  ports:
    - port: 8080