---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: applications
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: ssh://git@github.com/ramesh291989/example-environment

